name: Item added to project

on:
  issues:
    types: [opened] 

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: Dodaj zgłoszenie do projektu
      uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/2024-2025-AGH-Wstep-do-Informatyki/projects/15
        github-token: ${{ secrets.GITHUB_TOKEN }} 
